bearing_max: deg(180.00)
bearing_min: deg(-180.00)
range_max: 15.00
range_min: 0.00
std_dev_rr: 0.02
std_dev_rb: 0.0
std_dev_bb: deg(2.0) 
kappa: 0.0400
skip_beams: 4
target_diam: 0.0413
intensity_threshold: 11000.0

#det_prob:
#  - {range: 0.00, prob: 0.9900}
#  - {range: 2.36, prob: 0.9900}
#  - {range: 2.50, prob: 0.9365}
#  - {range: 2.75, prob: 0.8514}
#  - {range: 3.00, prob: 0.7804}
#  - {range: 3.25, prob: 0.7204}
#  - {range: 3.50, prob: 0.6689}
#  - {range: 3.75, prob: 0.6243}
#  - {range: 4.00, prob: 0.5853}
#  - {range: 4.25, prob: 0.5509}
#  - {range: 4.50, prob: 0.5203}
#  - {range: 4.75, prob: 0.4929}
#  - {range: 5.00, prob: 0.4682}

det_prob:
  - {range: 0.00, prob: 0.9900}
  - {range: 15.00, prob: 0.9900}
#  - {range: 2.50, prob: 0.9865}
#  - {range: 3.75, prob: 0.9814}
#  - {range: 4.00, prob: 0.9764}
#  - {range: 5.25, prob: 0.9704}
#  - {range: 5.50, prob: 0.9689}
#  - {range: 6.75, prob: 0.9643}
#  - {range: 7.00, prob: 0.9553}
#  - {range: 7.25, prob: 0.9409}
#  - {range: 8.50, prob: 0.9303}
#  - {range: 8.75, prob: 0.9229}
#  - {range: 10.00, prob: 0.9082}

target_types: ['person', 'chair']
#confusion_matrix: [0.9, 0.05, 0.05, 0.1, 0.8, 0.1, 0.15, 0.15, 0.7]
#confusion_matrix: [0.8, 0.15, 0.05, 0.2, 0.7, 0.1, 0.2, 0.25, 0.55]
confusion_matrix: [0.9, 0.1, 0.1, 0.9]
#confusion_matrix: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

map_service: "/static_map"
